
export const ACTIVATION_BEGIN = 'ACTIVATION_BEGIN';
export const ACTIVATION_CLEAR = 'ACTIVATION_CLEAR';
export const ACTIVATION_FAILURE = 'ACTIVATION_FAILURE';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';

//login
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const PASSWORD_EMAIL_BEGIN = 'PASSWORD_EMAIL_BEGIN';
export const PASSWORD_EMAIL_CLEAR = 'PASSWORD_EMAIL_CLEAR';
export const PASSWORD_EMAIL_FAILURE = 'PASSWORD_EMAIL_FAILURE';
export const PASSWORD_EMAIL_SUCCESS = 'PASSWORD_EMAIL_SUCCESS';

//password reset

export const PASSWORD_RESET_BEGIN = 'PASSWORD_RESET_BEGIN';
export const PASSWORD_RESET_CLEAR = 'PASSWORD_RESET_CLEAR';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';

//registration

export const REGISTRATION_BEGIN = 'REGISTRATION_BEGIN';
export const REGISTRATION_CLEAR = 'REGISTRATION_CLEAR';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';

export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';



//profile
export const   	PROFILE_CREATE_BEGIN  =  ' PROFILE_CREATE_BEGIN';
export const  	PROFILE_CREATE_SUCCESS  =  ' PROFILE_CREATE_SUCCESS';
export const     PROFILE_CREATE_FAILURE  =  'PROFILE_CREATE_SUCCESS';

export const      PROFILE_GET_BEGIN   =    'PROFILE_GET_BEGIN';
export const      PROFILE_GET_SUCCESS  =  'PROFILE_GET_BEGIN';
export const      PROFILE_GET_FAILURE   = 'PROFILE_GET_FAILURE';

export const     PROFILE_DELETE_BEGIN  = 'PROFILE_DELETE_BEGIN';
export const      PROFILE_DELETE_SUCCESS  = 'PROFILE_DELETE_SUCCESS';
export const      PROFILE_DELETE_FAILURE  = 'PROFILE_DELETE_FAILURE';

export const      PROFILE_UPDATE_BEGIN   = 'PROFILE_UPDATE_BEGIN';
export const      PROFILE_UPDATE_SUCCESS  = 'PROFILE_UPDATE_SUCCESS';
export const      PROFILE_UPDATE_FAILURE    = 'PROFILE_UPDATE_FAILURE';


//post


export const   	POST_CREATE_BEGIN  =  ' POST_CREATE_BEGIN';
export const  	POST_CREATE_SUCCESS  =  ' POST_CREATE_SUCCESS';
export const     POST_CREATE_FAILURE  =  'POST_CREATE_SUCCESS';

export const      POST_GET_BEGIN   =    'POST_GET_BEGIN';
export const      POST_GET_SUCCESS  =  'POST_GET_BEGIN';
export const      POST_GET_FAILURE   = 'POST_GET_FAILURE';

export const     POST_DELETE_BEGIN  = 'POST_DELETE_BEGIN';
export const      POST_DELETE_SUCCESS  = 'POST_DELETE_SUCCESS';
export const      POST_DELETE_FAILURE  = 'POST_DELETE_FAILURE';

export const      POST_UPDATE_BEGIN   = 'POST_UPDATE_BEGIN';
export const      POST_UPDATE_SUCCESS  = 'POST_UPDATE_SUCCESS';
export const      POST_UPDATE_FAILURE    = 'POST_UPDATE_FAILURE';


//news

export const NEWS_GET_BEGIN = 'NEWS_GET_BEGIN';
export const NEWS_GET_SUCCESS = 'NEWS_GET_SUCCESS';
export const NEWS_GET_FAILURE = 'NEWS_GET_FAILURE';


//comment


export const  COMMENT_CREATE_BEGIN  = 'COMMENT_CREATE_BEGIN';
export const COMMENT_CREATE_SUCCESS   = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_FAILURE   =  'COMMENT_CREATE_FAILURE'


export const COMMENT_UPDATE_BEGIN  = 'COMMENT_UPDATE_BEGIN';
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS';
export const COMMENT_UPDATE_FAILURE  = 'COMMENT_UPDATE_FAILURE';


export const COMMENT_DELETE_BEGIN 	= 'COMMENT_DELETE_BEGIN';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAILURE  = 'COMMENT_DELETE_FAILURE';


export const COMMENT_GET_BEGIN = 'COMMENT_GET_BEGIN';
export const COMMENT_GET_SUCCESS = 'COMMENT_GET_SUCCESS';
export const COMMENT_GET_FAILURE = 'COMMENT_GET_FAILURE';


//vacancy

export const  VACANCY_CREATE_BEGIN  = 'VACANCY_CREATE_BEGIN';
export const VACANCY_CREATE_SUCCESS   = 'VACANCY_CREATE_SUCCESS';
export const VACANCY_CREATE_FAILURE   =  'VACANCY_CREATE_FAILURE'


export const VACANCY_UPDATE_BEGIN  = 'VACANCY_UPDATE_BEGIN';
export const VACANCY_UPDATE_SUCCESS = 'VACANCY_UPDATE_SUCCESS';
export const VACANCY_UPDATE_FAILURE  = 'VACANCY_UPDATE_FAILURE';


export const VACANCY_DELETE_BEGIN 	= 'VACANCY_DELETE_BEGIN';
export const VACANCY_DELETE_SUCCESS = 'VACANCY_DELETE_SUCCESS';
export const VACANCY_DELETE_FAILURE  = 'VACANCY_DELETE_FAILURE';


export const VACANCY_GET_BEGIN = 'VACANCY_GET_BEGIN';
export const VACANCY_GET_SUCCESS = 'VACANCY_GET_SUCCESS';
export const VACANCY_GET_FAILURE = 'VACANCY_GET_FAILURE';









